version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py
  builder: dirhtml

formats:
  - pdf
  - epub

python:
  install:
    - method: pip
      path: implementations/python
      extra_requirements:
        - docs
